// Action vocabulary shared by UI and engine.
export const A = {
  RESET: 'RESET',
  SELECT_CONV: 'SELECT_CONV',
  RESET_CONV: 'RESET_CONV',
  TOGGLE_ROSTER: 'TOGGLE_ROSTER',
  SET_UI: 'SET_UI',

  ADD_MESSAGE: 'ADD_MESSAGE',
  PATCH_MESSAGE: 'PATCH_MESSAGE',
  SET_TYPING: 'SET_TYPING',
  SET_CHIPS: 'SET_CHIPS',
  SET_VOICE: 'SET_VOICE',

  SET_BOT_STATUS: 'SET_BOT_STATUS',
  PATCH_BOT: 'PATCH_BOT',
  ADD_BOT_TO_ROSTER: 'ADD_BOT_TO_ROSTER',
  ADD_BOT_TO_CREW: 'ADD_BOT_TO_CREW',
  SAVE_CREW: 'SAVE_CREW',
  PATCH_DRAFT_BOT: 'PATCH_DRAFT_BOT',

  LIVE_OPEN: 'LIVE_OPEN',
  LIVE_BACK: 'LIVE_BACK',
  LIVE_CLOSE: 'LIVE_CLOSE',
  LIVE_EXPAND: 'LIVE_EXPAND',
  LIVE_SET_STEP: 'LIVE_SET_STEP',

  PUSH_APPROVAL: 'PUSH_APPROVAL',
  DECIDE_APPROVAL: 'DECIDE_APPROVAL',
  PATCH_APPROVAL: 'PATCH_APPROVAL',
  ADD_ROUTINE: 'ADD_ROUTINE',

  ADD_BOT: 'ADD_BOT',
  KNOWLEDGE_ADD_UPLOAD: 'KNOWLEDGE_ADD_UPLOAD',
  KNOWLEDGE_SOURCE: 'KNOWLEDGE_SOURCE',
  KNOWLEDGE_EDIT_LEARNED: 'KNOWLEDGE_EDIT_LEARNED',
  KNOWLEDGE_SOP: 'KNOWLEDGE_SOP',
  KNOWLEDGE_BRANCH: 'KNOWLEDGE_BRANCH',
  CONNECTOR: 'CONNECTOR',
  PATCH_DOC: 'PATCH_DOC',
  SET_DOC: 'SET_DOC',

  ENGINE_SET_RUN: 'ENGINE_SET_RUN',
  ENGINE_CLEAR_RUN: 'ENGINE_CLEAR_RUN',
}
